### ISSUE TITLE
InfluxDB can't parse `null` values for measurements (v0.13.0)

### ISSUE THREAD

**Issue by vanilladuck** [dropbox/llama-archive#10]
```InfluxDBClientError: 400: {"error":"partial write:\nunable to parse 'loss,tag1=a,dst_host=host1,tag2=b,src_host=host2 1479341324000000000'```

Is produced in the `llama_scraper` logs when the following data is presented by a `llama_collector` (obtained by `$ curl http://<collector>:5000/influxdata`)

``` {
        "fields": {
            "value": null
        },
        "tags": {
            "tag1": "a",
            "tag2": "b",
            "dst_host": "host1",
            "src_host": "host2"
        },
        "time": 1479341534000000000,
        "measurement": "loss"
    },
```

**Comment by jathanism** [comment]
Based on my observation this is the result of the host being pinged not responding (such as a bad hostname).

I think if we address the fact that a host didn't response to hping or had a null value this wouldn't happen. Also, perhaps it should be logged and stored in an "error" time series?

**Comment by dmar42** [comment]
#27 looks like a symptom of how this is being handled
